#!/bin/bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

root=$(dirname "${0}" | while read -r a; do cd "${a}" && pwd && break; done)
export root
# shellcheck source=./common.sh
source "${root}/common.sh"

payload=$(mktemp "${TMPDIR}/sonarqube-resource-check.XXXXXX")
cat > "${payload}" <&0

DEBUG="$(jq -r '.source.__debug // "false"' < "${payload}")"
enable_debugging "${DEBUG}"

latest_version=$(jq -r '.version.ce_task_id // ""' < "${payload}")
if [[ -n "${latest_version}" ]]; then
	jq -n "[
		{ ce_task_id: \"${latest_version}\"}
	]" >&3
else
	jq -n "[]" >&3
fi
